export enum FileTypeBackend {
  TERM_COMMITMENT = 'TERM_COMMITMENT',
  STUDENT_SELF_EVALUATION = 'STUDENT_SELF_EVALUATION',
  INTERNSHIP_GRANTOR_EVALUATION = 'INTERNSHIP_GRANTOR_EVALUATION',
  SUPERVISOR_EVALUATION = 'SUPERVISOR_EVALUATION',
  RENEWAL_DOCUMENT = 'RENEWAL_DOCUMENT',
  INTERNSHIP_CERTIFICATE = 'INTERNSHIP_CERTIFICATE',
}
